### ISSUE TITLE
required customize color selection and clear screen features

### ISSUE THREAD

**Issue by RitheeshBaradwaj** [developers-cosmos/Air-Writing-To-Speech#2]
- Feature, which allows the user to select different colors is needed.
- Clear Screen feature is required.
- The current frame needs to be saved as an image in a directory for any event occurrence.
@santhoshbandaru please refer to the branch, feature_air2img for driver code.

**Comment by santhoshbandaru** [comment]
I just added the code with given requirements in the **feature_air2img** branch. @RitheeshBaradwaj  review the code and if you need any changes send those details

**Comment by RitheeshBaradwaj** [comment]
@santhoshbandaru application is working well. 
- Now I want you to add a feature that asks the users to enter a color to detect, take red and green color as a reference, use Tkinter to select a color.
- Please visit <b>find_hsvRanges</b> in <b>feature_air2img</b> branch as a reference to know how to find the HSV lower and upper ranges for a specific object or color.<br>
![image](https://user-images.githubusercontent.com/48406715/84600308-f448e700-ae95-11ea-819f-482586e856ed.png)

**Comment by santhoshbandaru** [comment]
Yeah, with the help of **find_hsvRanges** . I written the code with user choice of picking colors and uploaded it in same branch with **air2img_choice_color_with_color** folder @RitheeshBaradwaj review the code and if anything won't work let me know

**Comment by RitheeshBaradwaj** [comment]
The application can detect the colors specified. Now please make a GUI with Tkinter to accept the user's choice! @santhoshbandaru

**Comment by santhoshbandaru** [comment]
I just uploaded code with a GUI in **air2img_GUI** folder @RitheeshBaradwaj review it and let me know any changes if required

**Comment by RitheeshBaradwaj** [comment]
@santhoshbandaru It's perfect!
please update the code with the capture button and put it in main.py

**Comment by santhoshbandaru** [comment]
Yeah, I updated my work as **air2_img_with_all** there we can capture screen using either keyboard or I added as a icon in the screen to capture and clear. @RitheeshBaradwaj review it once

**Comment by santhoshbandaru** [comment]
@RitheeshBaradwaj I just updated code in same location check once

**Comment by RitheeshBaradwaj** [comment]
It's working only in some cases, please once check it. Try to increase the entire canvas size and also buttons size

**Comment by santhoshbandaru** [comment]
just now I updated the code please  go through it once  @RitheeshBaradwaj

**Comment by RitheeshBaradwaj** [comment]
@santhoshbandaru the application is working as expected!
The issue is resolved.
